# Generated by Django 3.1.4 on 2021-09-15 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CRR',
        ),
        migrations.RemoveField(
            model_name='image_uploader',
            name='name',
        ),
        migrations.AlterField(
            model_name='image_uploader',
            name='image',
            field=models.ImageField(upload_to='app/static/asset/Image_Folder'),
        ),
    ]
